# Generated by Django 4.2.3 on 2023-07-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estamento',
            fields=[
                ('id_estamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'campus_diverso_estamento',
            },
        ),
        migrations.CreateModel(
            name='ExpresionGenero',
            fields=[
                ('id_expresion_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_expresion_genero', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'campus_diverso_expresion_genero',
            },
        ),
        migrations.CreateModel(
            name='IdentidadGenero',
            fields=[
                ('id_identidad_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_identidad_genero', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'campus_diverso_identidad_genero',
            },
        ),
        migrations.CreateModel(
            name='InformacionGeneral',
            fields=[
                ('id_informacion_general', models.AutoField(primary_key=True, serialize=False)),
                ('dedicacion_externa', models.CharField(max_length=100)),
                ('tipo_acompanamiento_recibido', models.CharField(max_length=70)),
                ('observacion_tipo_acompanamiento_recibido', models.TextField()),
                ('tipo_entidad_acompanamiento_recibido', models.TextField()),
                ('tipo_profesional_acompanamiento_recibido', models.TextField()),
                ('calificacion_acompanamiento_recibido', models.IntegerField(null=True)),
                ('motivo_calificacion_acompanamiento', models.TextField(null=True)),
                ('actividades_especificas_tiempo_libre', models.TextField()),
                ('observacion_general_actividades_especificas_tiempo_libre', models.TextField()),
                ('observacion_general_fuente_de_ingresos', models.TextField()),
                ('observacion_general_relacion_familiar', models.TextField()),
                ('relacion_familiar', models.IntegerField()),
                ('observacion_general_redes_de_apoyo', models.TextField()),
                ('observacion_general_factores_de_riesgo', models.TextField()),
                ('creencia_religiosa', models.TextField()),
                ('encuentro_inicial', models.CharField(max_length=30)),
                ('observacion_horario', models.TextField(default='Sin observación')),
                ('origen_descubrimiento_campus_diverso', models.CharField(max_length=300)),
                ('comentarios_o_sugerencias_de_usuario', models.TextField()),
            ],
            options={
                'db_table': 'campus_diverso_informacion_general',
            },
        ),
        migrations.CreateModel(
            name='OcupacionActual',
            fields=[
                ('id_ocupacion_actual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ocupacion_actual', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'campus_diverso_ocupacion_actual',
            },
        ),
        migrations.CreateModel(
            name='OrientacionSexual',
            fields=[
                ('id_orientacion_sexual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_orientacion_sexual', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'campus_diverso_orientacion_sexual',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('incluir_correo_en_respuesta', models.BooleanField(default=False)),
                ('nombre_identitario', models.CharField(max_length=150)),
                ('nombre_y_apellido', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('estrato_socioeconomico', models.IntegerField()),
                ('ciudad_nacimiento', models.CharField(default='Ciudad no especificada', max_length=100)),
                ('municipio_nacimiento', models.CharField(default='Municipio no especificado', max_length=100)),
                ('corregimiento_nacimiento', models.CharField(default='Corregimiento no especificado', max_length=100)),
                ('departamento_nacimiento', models.CharField(max_length=100)),
                ('pais_nacimiento', models.CharField(max_length=100)),
                ('ciudad_residencia', models.CharField(default='Ciudad no especificada', max_length=100)),
                ('municipio_residencia', models.CharField(default='Municipio no especificado', max_length=100)),
                ('corregimiento_residencia', models.CharField(default='Corregimiento no especificado', max_length=100)),
                ('zona_residencial', models.CharField(max_length=100)),
                ('direccion_residencia', models.CharField(max_length=200)),
                ('barrio_residencia', models.CharField(max_length=150)),
                ('comuna_barrio', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=30)),
                ('identidad_etnico_racial', models.CharField(max_length=70)),
                ('nombre_persona_de_confianza', models.TextField()),
                ('relacion_persona_de_confianza', models.TextField()),
                ('telefono_persona_de_confianza', models.TextField()),
            ],
            options={
                'db_table': 'campus_diverso_persona',
            },
        ),
        migrations.CreateModel(
            name='PertenenciaGrupoPoblacional',
            fields=[
                ('id_grupo_poblacional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo_poblacional', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'campus_diverso_pertenencia_grupo_poblacional',
            },
        ),
        migrations.CreateModel(
            name='Pronombre',
            fields=[
                ('id_pronombre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pronombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'campus_diverso_pronombre',
            },
        ),
        migrations.CreateModel(
            name='RespuestaCambioDocumento',
            fields=[
                ('id_respuesta_cambio_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_respuesta_cambio_documento', models.TextField()),
            ],
            options={
                'db_table': 'campus_diverso_respuesta_cambio_documento',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_profesional', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='modulo_campus_diverso.persona')),
            ],
            options={
                'db_table': 'campus_diverso_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='RedApoyo',
            fields=[
                ('id_red_apoyo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_red_apoyo', models.CharField(max_length=200)),
                ('observacion_red_apoyo', models.TextField(blank=True, default='Sin observacion')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='redes_de_apoyo', to='modulo_campus_diverso.informaciongeneral')),
            ],
            options={
                'db_table': 'campus_diverso_red_apoyo',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='pertenencia_grupo_poblacional',
            field=models.ManyToManyField(max_length=300, related_name='personas', to='modulo_campus_diverso.pertenenciagrupopoblacional'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_general', to='modulo_campus_diverso.persona'),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='ocupaciones_actuales',
            field=models.ManyToManyField(max_length=200, related_name='informaciones_generales', to='modulo_campus_diverso.ocupacionactual'),
        ),
        migrations.CreateModel(
            name='InformacionAcademica',
            fields=[
                ('id_informacion_academica', models.AutoField(primary_key=True, serialize=False)),
                ('pertenencia_univalle', models.BooleanField()),
                ('sede_universidad', models.CharField(max_length=20)),
                ('nombre_programa_academico', models.CharField(max_length=100)),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('semestre_academico', models.IntegerField()),
                ('estamentos', models.ManyToManyField(max_length=100, to='modulo_campus_diverso.estamento')),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_academica', to='modulo_campus_diverso.persona')),
            ],
            options={
                'db_table': 'campus_diverso_informacion_academica',
            },
        ),
        migrations.CreateModel(
            name='FuenteIngresos',
            fields=[
                ('id_fuente_ingresos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fuente_ingresos', models.CharField(max_length=200)),
                ('observacion_fuente_ingresos', models.TextField(blank=True, default='Sin Observación')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_de_ingresos', to='modulo_campus_diverso.informaciongeneral')),
            ],
            options={
                'db_table': 'campus_diverso_fuente_ingresos',
            },
        ),
        migrations.CreateModel(
            name='FactorRiesgo',
            fields=[
                ('id_factor_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_factor_riesgo', models.CharField(max_length=200)),
                ('observacion_factor_riesgo', models.TextField(blank=True, default='Sin observacion')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='factores_de_riesgo', to='modulo_campus_diverso.informaciongeneral')),
            ],
            options={
                'db_table': 'campus_diverso_factor_riesgo',
            },
        ),
        migrations.CreateModel(
            name='EncuentroDiaHora',
            fields=[
                ('id_encuentro_dia_hora', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=20)),
                ('hora', models.TimeField()),
                ('id_informacion_general', models.ManyToManyField(blank=True, related_name='encuentro_dias_horas', to='modulo_campus_diverso.informaciongeneral')),
            ],
            options={
                'db_table': 'campus_diverso_encuentro_dia_hora',
            },
        ),
        migrations.CreateModel(
            name='DocumentosAutorizacion',
            fields=[
                ('id_documentos_autorizacion', models.AutoField(primary_key=True, serialize=False)),
                ('autorizacion_manejo_de_datos', models.BooleanField()),
                ('firma_consentimiento_informado', models.BooleanField()),
                ('firma_terapia_hormonal', models.BooleanField(blank=True, null=True)),
                ('documento_digital_y_archivo', models.BooleanField(blank=True, null=True)),
                ('apgar_familiar', models.IntegerField()),
                ('ecomapa', models.BooleanField(blank=True, null=True)),
                ('arbol_familiar', models.BooleanField(blank=True, null=True)),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_autorizacion', to='modulo_campus_diverso.persona')),
            ],
            options={
                'db_table': 'campus_diverso_documentos_autorizacion',
            },
        ),
        migrations.CreateModel(
            name='DiversidadSexual',
            fields=[
                ('id_diversidad_sexual', models.AutoField(primary_key=True, serialize=False)),
                ('cambio_nombre_sexo_documento', models.CharField(max_length=50)),
                ('recibir_orientacion_cambio_en_documento', models.BooleanField()),
                ('expresiones_de_genero', models.ManyToManyField(max_length=200, to='modulo_campus_diverso.expresiongenero')),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diversidad_sexual', to='modulo_campus_diverso.persona')),
                ('identidades_de_genero', models.ManyToManyField(max_length=200, to='modulo_campus_diverso.identidadgenero')),
                ('orientaciones_sexuales', models.ManyToManyField(max_length=200, to='modulo_campus_diverso.orientacionsexual')),
                ('pronombres', models.ManyToManyField(max_length=50, to='modulo_campus_diverso.pronombre')),
                ('respuestas_cambio_documento', models.ManyToManyField(to='modulo_campus_diverso.respuestacambiodocumento')),
            ],
            options={
                'db_table': 'campus_diverso_diversidad_sexual',
            },
        ),
        migrations.CreateModel(
            name='ConvivenciaVivienda',
            fields=[
                ('id_convivencia_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convivencia_vivienda', models.CharField(max_length=200)),
                ('observacion_convivencia_vivienda', models.TextField(blank=True, default='Sin observacion')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='convivencias_en_vivienda', to='modulo_campus_diverso.informaciongeneral')),
            ],
            options={
                'db_table': 'campus_diverso_convivencia_vivienda',
            },
        ),
        migrations.CreateModel(
            name='ActividadTiempoLibre',
            fields=[
                ('id_actividad_tiempo_libre', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad_tiempo_libre', models.CharField(max_length=200)),
                ('observacion_actividad_tiempo_libre', models.TextField(blank=True, default='Sin observación')),
                ('id_informacion_general', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_tiempo_libre', to='modulo_campus_diverso.informaciongeneral')),
            ],
            options={
                'db_table': 'campus_diverso_actividad_tiempo_libre',
            },
        ),
    ]
