# Generated by Django 4.2.1 on 2023-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estamento',
            name='nombre_estamento',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='expresiongenero',
            name='nombre_expresion_genero',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='identidadgenero',
            name='nombre_identidad_genero',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='estamentos',
            field=models.ManyToManyField(max_length=100, related_name='id_informacion_academica', to='modulo_campus_diverso.estamento'),
        ),
        migrations.AlterField(
            model_name='ocupacionactual',
            name='nombre_ocupacion_actual',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='orientacionsexual',
            name='nombre_orientacion_sexual',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='pertenenciagrupopoblacional',
            name='nombre_grupo_poblacional',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='pronombre',
            name='nombre_pronombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='respuestacambiodocumento',
            name='nombre_respuesta_cambio_documento',
            field=models.TextField(unique=True),
        ),
    ]
