# Generated by Django 4.2.4 on 2023-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0002_alter_estamento_nombre_estamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompañamientoRecibido',
            fields=[
                ('id_ocupacion_actual', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acompañamiento_recibido', models.CharField(max_length=200)),
                ('observacion_acompanamiento_recibido', models.TextField(blank=True, default='Sin observaciones')),
            ],
            options={
                'db_table': 'Acompañamiento_recibido',
            },
        ),
        migrations.RenameField(
            model_name='informaciongeneral',
            old_name='encuentro_inicial',
            new_name='decision_encuentro_inicial_con_profesional',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='observacion_general_relacion_familiar',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='observacion_tipo_acompanamiento_recibido',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='tipo_acompanamiento_recibido',
        ),
        migrations.RemoveField(
            model_name='informaciongeneral',
            name='tipo_profesional_acompanamiento_recibido',
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='calificacion_relacion_familiar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='nombre_eps',
            field=models.CharField(default='Sin observacion', max_length=200),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='regimen_eps',
            field=models.CharField(default='Sin regimen', max_length=50),
        ),
        migrations.AddField(
            model_name='informaciongeneral',
            name='tiene_eps',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
    ]
