# Generated by Django 4.2.4 on 2023-08-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0003_acompañamientorecibido_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acompañamientorecibido',
            table='campus_diverso_acompañamiento_recibido',
        ),
    ]
