# Generated by Django 4.2.4 on 2023-08-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0005_informacionprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionprofesional',
            name='id_informacion_general',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='nombre_profesional_que_brindo_atencion', to='modulo_campus_diverso.informaciongeneral'),
        ),
    ]
