# Generated by Django 4.2.5 on 2023-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0007_alter_documentosautorizacion_apgar_familiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciongeneral',
            name='decision_encuentro_inicial_con_profesional',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='dedicacion_externa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='observacion_general_actividades_especificas_tiempo_libre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='tipo_entidad_acompanamiento_recibido',
            field=models.TextField(null=True),
        ),
    ]
