# Generated by Django 4.2.5 on 2023-10-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0009_alter_acompañamientorecibido_nombre_acompañamiento_recibido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convivenciavivienda',
            name='id_informacion_general',
        ),
        migrations.AlterField(
            model_name='acompañamientorecibido',
            name='observacion_acompanamiento_recibido',
            field=models.TextField(blank=True, default='Sin observaciones', null=True),
        ),
    ]
