# Generated by Django 4.2.5 on 2023-10-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_campus_diverso', '0012_alter_acompañamientorecibido_nombre_acompañamiento_recibido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversidadsexual',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DiversidadSexual', to='modulo_campus_diverso.persona'),
        ),
        migrations.AlterField(
            model_name='documentosautorizacion',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentosAutorizacion', to='modulo_campus_diverso.persona'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='InformacionAcademica', to='modulo_campus_diverso.persona'),
        ),
        migrations.AlterField(
            model_name='informaciongeneral',
            name='id_persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='InformacionGeneral', to='modulo_campus_diverso.persona'),
        ),
    ]
